services:
  app:
    build:
      context: .
      target: dev
    healthcheck:
      test: sh -c 'apk add curl; curl http://localhost:3000'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - 5000:3000
    depends_on:
      - flagd-one
      - flagd-two
    volumes:
      - .:/app
    environment:
      - FLAGD_HOST_ONE=flagd-one
      - FLAGD_HOST_TWO=flagd-two
      - MORE_FUN=${MORE_FUN}

  flagd-one:
    image: ghcr.io/open-feature/flagd:v0.11.4
    command: start --uri file:/etc/flagd/flags.flagd.json
    volumes:
      - ./flags.flagd.one.json:/etc/flagd/flags.flagd.json
    ports:
      - 8013:8013
      - 8016:8016

  flagd-two:
    image: ghcr.io/open-feature/flagd:v0.11.4
    command: start --uri file:/etc/flagd/flags.flagd.json
    volumes:
      - ./flags.flagd.two.json:/etc/flagd/flags.flagd.json
    ports:
      - 8014:8013
      - 8015:8016
