services:
  app:
    build:
      context: .
      target: dev
    healthcheck:
      test: sh -c 'apk add curl; curl http://localhost:3000'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - 5000:3000
    depends_on:
      - flagd
    volumes:
      - .:/app
    environment:
      - FLAGD_HOST=flagd
      - OPENFEATURE_PROVIDER=${OPENFEATURE_PROVIDER:-flagd}
      - SHOW_WELCOME_MESSAGE=${SHOW_WELCOME_MESSAGE:-false}
      - WELCOME_MESSAGE=${WELCOME_MESSAGE:-Hello World set by Environment!}

  flagd:
    image: ghcr.io/open-feature/flagd:v0.11.4
    command: start --uri file:/etc/flagd/flags.flagd.json
    volumes:
      - ./flags.flagd.json:/etc/flagd/flags.flagd.json
    ports:
      - 8013:8013
      - 8016:8016
